version: "3.3"

services:
  mongodb:
    image: mongo:5.0.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  parse-server:
    image: parseplatform/parse-server
    restart: always
    ports:
      - ${PARSE_PORT}:1337
    depends_on:
      - "mongodb"
    command: --appId ${PARSE_APPLICATION_ID} --masterKey ${PARSE_MASTER_KEY} --databaseURI mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:${MONGO_PORT}
